### ISSUE TITLE
Silly not logging

### ISSUE THREAD

**Issue by krakenik111** [malezjaa/prime-console#8]
**Describe the bug**
Hi, I am using your package, and my silly message is not showing. Can you help me?

**To Reproduce**
1. download package
2. create logger class
3. use silly function

**Expected behavior**
Should login

I have no errors.

**Comment by malezjaa** [comment]
Hi, I can help you. Can you just show mi how your code looks?

**Comment by krakenik111** [comment]
import { Logger } from "prime-console";

const log = new Logger({
  config: {
    silly: {
      color: "black",
      background: "green",},
  }, time: {
    color: "yellow",
  },
});

log.silly("test");

**Comment by malezjaa** [comment]
Ok, you need to set logLevel to 5. This will log every log level to your console.

```ts
import { Logger } from "prime-console";

const log = new Logger({
config: {
  silly: {
    color: "black",
    background: "green",
  },
}, 
time: {
  color: "yellow",
},
logLevel: 5
});

log.silly("test");
```

**Comment by malezjaa** [comment]
This is how your code should look like. Does it works?

**Comment by krakenik111** [comment]
Yes, thank you!
