### ISSUE TITLE
Sry, for asking again.

### ISSUE THREAD

**Issue by krakenik111** [malezjaa/prime-console#9]
const log = new Logger({
  config: {
    error: {
      color: "black",
      background: "green",
    },
  },
  time: {
    color: "yellow",
  },
  logLevel: 5,
  file: {
    dir: "../logs/app",
    name: "logfile",
    format: "json",
  },
});

Hey, this is my code and i don't know why the log file is not showing. (sorry i am noob)

**Comment by malezjaa** [comment]
Yeah, no problem. Just replace ../logs/app with ./logs/app 
We use a single dot ("./") or two dots ("../") before a folder name to refer to the current folder or the parent folder in the folder tree. I hope this helps!

**Comment by krakenik111** [comment]
No I understand. Thanks.
